@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\Structure_Type\MDSYS.SDO_GEOMETRY.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\Structure_Type\XMLTYPE.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\Table\Comanda.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\Table\Comanda_Constraints.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\Table\CPU.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\Table\CPU_Constraints.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\Table\CPU_GPU.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\Table\CPU_GPU_Constraints.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\Table\CPU_RAM.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\Table\CPU_RAM_Constraints.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\Table\Detalii_Comanda.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\Table\Detalii_Comanda_Constraints.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\Table\GPU.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\Table\GPU_Constraints.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\Table\RAM.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\Table\RAM_Constraints.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\ForeignKey\Comanda_CPU_fk.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\ForeignKey\Comanda_Detalii_comanda.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\ForeignKey\Comanda_GPU_fk.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\ForeignKey\Comanda_RAM_fk.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\ForeignKey\CPU_GPU_CPU_FK.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\ForeignKey\CPU_GPU_GPU_FK.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\ForeignKey\CPU_RAM_CPU_FK.sql
@@proiect4\Relational_1\Oracle_Database_12c\DataObjects\ForeignKey\CPU_RAM_RAM_FK.sql
@@proiect4\Relational_1\Oracle_Database_12c\Code\Trigger\trg_Comanda_BRIU.pls
@@proiect4\Relational_1\Oracle_Database_12c\Code\Trigger\trg_Detalii_Comanda_BRIU.pls
